AllCops:
  Exclude:
  - 'bin/**/*'
  - 'db/**/*'
  - 'etc/**/*'
  - 'frontend/node_modules/**/*'
  - 'tmp/**/*'
  TargetRubyVersion: 2.7

AsciiComments:
  Enabled: false
CyclomaticComplexity:
  Max: 8
Metrics/AbcSize:
  Max: 64
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  CountComments: false
  Max: 64
Metrics/ModuleLength:
  Enabled: false
Naming/VariableNumber:
  EnforcedStyle: snake_case
  CheckSymbols: false
Security/YAMLLoad:
  # https://github.com/gollum/gollum/issues/1579
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
