AllCops:
  Exclude:
  - 'bin/**/*'
  - 'db/**/*'
  - 'etc/**/*'
  - 'frontend/node_modules/**/*'
  - 'tmp/**/*'
  TargetRubyVersion: 2.6

AsciiComments:
  Enabled: false
AlignParameters:
  Enabled: false
CyclomaticComplexity:
  Max: 7
GlobalVars:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Metrics/AbcSize:
  Max: 64
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  CountComments: false
  Max: 64
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 8
Security/YAMLLoad:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/SymbolProc:
  Enabled: false
