development:
  clients:
    default:
      database: <%= ENV['MONGO_DB'] %>
      hosts:
        - <%= ENV['MONGO_HOST'] %>:<%= ENV['MONGO_PORT'] %>
  options:
    raise_not_found_error: true
    use_utc: true

test:
  clients:
    default:
      database: <%= ENV['MONGO_DB_TEST'] %>
      hosts:
        - <%= ENV['MONGO_HOST'] %>:<%= ENV['MONGO_PORT'] %>
  options:
    raise_not_found_error: true
    use_utc: true

production:
  clients:
    default:
      database: <%= ENV['MONGO_DB'] %>
      hosts:
        - <%= ENV['MONGO_HOST'] %>:<%= ENV['MONGO_PORT'] %>
  options:
    raise_not_found_error: true
    use_utc: true
