default: &default
  clients:
    default:
      database: <%= ENV['MONGO_DB'] %>
      hosts:
        - <%= ENV['MONGO_HOST'] %>:<%= ENV['MONGO_PORT'] %>
  options:
    raise_not_found_error: false
    use_utc: true

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
